### PR TITLE
feat: set preset language to match app language

### PR DESCRIPTION
**Pull request by ErikSin**
Sets the language of presets based on app language.

### CODE REVIEW

**Review by achou11 — COMMENTED** [review]
From my understanding, the `lang` option is available for _all_ datatype method calls e.g. `getByDocId()`, `getByVersionId()`, etc. Shouldn't we update all of the relevant queries to specify this? Otherwise we would get inconsistencies in the UI based on which queries are being used.

**Comment by ErikSin** [comment]
> From my understanding, the `lang` option is available for _all_ datatype method calls e.g. `getByDocId()`, `getByVersionId()`, etc. Shouldn't we update all of the relevant queries to specify this? Otherwise we would get inconsistencies in the UI based on which queries are being used.

I believe that this is the only query. we don't ever call `preset.getByDocId()` or `preset.getByVersionId()` anywhere in front end.

**Comment by achou11** [comment]
> I believe that this is the only query. we don't ever call `preset.getByDocId()` or `preset.getByVersionId()` anywhere in front end.

Ah ok. Is it okay that only the presets are returning the translated versions (e.g. we don't need to do something similar for fields)?

**Comment by ErikSin** [comment]
> > I believe that this is the only query. we don't ever call `preset.getByDocId()` or `preset.getByVersionId()` anywhere in front end.
> 
> Ah ok. Is it okay that only the presets are returning the translated versions (e.g. we don't need to do something similar for fields)?

hmmm good question...ill look into that

**Comment by ErikSin** [comment]
ok! yeah, it looks like the fields can be translated!

**Comment by achou11** [comment]
> ok! yeah, it looks like the fields can be translated!

just to be clear, _all_ datatypes (e.g.  observation, track, field, and preset) can technically be translated i.e. any call to `getByDocId()`, `getByVersionId()`, and `getMany()` accept that `lang` option, hence the first question I had. I think for the purposes of the config-related UI, getting the translated fields and presets is sufficient, but probably need a follow up to update other relevant datatype queries to do the same thing.

**Review by achou11 — APPROVED** [review]
Should create a follow-up issue to pass in that lang option to other relevant queries

**Pull request merged**
