### PR TITLE
chore: add types for `react-native-scale-bar`

### PR DESCRIPTION
**Pull request by EvanHahn**
*This change is not urgent.* I noticed this while working on something else.

This is a types-only change, adding type definitions for this dependency.

They are lifted from [the dependency's internal Flow types][0].

[0]: https://github.com/felixgourdeau/ScaleBar/blob/cbe01e1e3c215d8acb599723cd9d87db0e63bdb4/index.js#L8-L13

### CODE REVIEW

**Comment by achou11** [comment]
@cimigree fixed that issue via https://github.com/digidem/comapeo-mobile/pull/567/commits/a8a4bc8793874bf38e335d7e2eff2e7ac94e92c4

Now getting a proper type error where that component is used

image

**Comment by EvanHahn** [comment]
Fixing this now. I did not do a great job with this PR.

**Comment by EvanHahn** [comment]
Should be fixed. Can't believe I didn't see the type error!

**Review by cimigree — APPROVED** [review]
I restarted my TS server and now it is fine! Sorry for any confusion.

**Comment by EvanHahn** [comment]
> Sorry for any confusion.

Nah, this was my mistake.

**Pull request merged**
