### PR TITLE
Menu fixes

### LINKED ISSUE #770: Hamburger menu fixes
A list of improvements to make to the menu, see notion for notes : https://www.notion.so/digidem/Correction-Fixes-for-Hamburger-menu-10b1b08162d58084b0a6d0d29a83492a

- [x] Make correction— menu today closes when tapping outside of it. That is not what we initially outlined. Menu should not close when tapped outside of it. Below is the screenshot we sent SWM 
- [x] Move About Mapeo to bottom and add divider
- [x]  Sizing of header (grey background) too large
- [x]  Double check the fonts and responsive sizing
- [x]  Correct the order of the menu items (Security lives inside App Settings). This is a full menu path (the blue is highlighting the paths tapped). Also lives in [[Figma](https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2910-2276&t=0IWXnCwwYCqnx6rk-1)](https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=2910-2276&t=0IWXnCwwYCqnx6rk-1)

### PR DESCRIPTION
**Pull request by ErikSin**
Closes #770

image

### CODE REVIEW

**Review by cimigree — COMMENTED** [review]
The transparent background seems to work although it is weird with the status bar over the screen (see photo in Status bar link). Is there any way to change that?
Two small questions.
Is the Privacy Policy icon really supposed to be the lock as it is in the designs because there is a different icon being used?
The menu items seem very close to the top in the sub menus, that is closer than the designs appear but I can't figure out how to see the actual designed spacing.


[Menu items close to top](https://photos.app.goo.gl/M74tZSXRJtjCHkM96)

Design:
Screenshot 2024-10-23 at 1 15 08 PM

[Status bar](https://photos.app.goo.gl/6h83pepsVePCaWzf7)

**Review by cimigree — COMMENTED** [review]
I like the reusable Full Screen Menu List and Menu List Item components! 

It is so hard to know what the UI should look like because the ticket references Figma which looks nothing like what is in the ticket! (In Figma, Security is not under app settings there, for example, and there is no dividing line!) And in the ticket the lock icon is used for Privacy Policy and the Project Settings are in a slightly different order (Project Configuration is between Device Name and Your Team). Which did you use? How did you know?

I see you moved the menu items down from the header. Now the individual items within the menu are evenly spaced, but that is not how it appears in the designs in the ticket.

I still think the status bar is strange if you have to scroll (small phones or enlarged display/ text) but I know those are very difficult to work around.

**Comment by ErikSin** [comment]
It should be following this menu: https://www.figma.com/design/iUeC0Qzhb4H0unuPfxQAsM/(Mobile)-CoMapeo?node-id=3335-2065&t=3aegivSUuOhHqYuK-1

**Comment by cimigree** [comment]
Ok well in that case my comments still apply.
In the Figma the lock icon is used for Privacy Policy
In the Figma, the Project Settings are in a slightly different order (in Figma, Configuration is between Device Name and Your Team and it is called Configuration, not Project Configuration as you have it).

**Comment by ErikSin** [comment]
Ok I have updated the ordering and icon.

I also updated the drawer to use the new `MenuListItem` instead of the `< List/>`

**Review by cimigree — APPROVED** [review]

**Pull request merged**
