### PR TITLE
feat: added loading spinner

### PR DESCRIPTION
**Pull request by ErikSin**
Added a loading spinner: 

 https://github.com/digidem/CoMapeo-mobile/assets/67773827/9d7b8341-0e70-4311-b390-30acbec2db3f

### CODE REVIEW

**Review by achou11 — APPROVED** [review]
probably would make the commit title a little specific but otherwise changes lgtm!

**Comment by ErikSin** [comment]
Im realizing that this pattern doesnt actually make sense. if there is an error, we should be catching it BEFORE this screen. the loader should happen the screen before...its just complicates thing because of the conditional rendering @achou11

**Comment by achou11** [comment]
> Im realizing that this pattern doesnt actually make sense. if there is an error, we should be catching it BEFORE this screen. the loader should happen the screen before...its just complicates thing because of the conditional rendering @achou11

yeah pretty sure I had brought this up before: https://github.com/digidem/CoMapeo-mobile/pull/73#discussion_r1356900866

think the suggestion i made there is still potentially useful: https://github.com/digidem/CoMapeo-mobile/pull/73#discussion_r1357246210

**Comment by ErikSin** [comment]
> think the suggestion i made there is still potentially useful: [#73 (comment)](https://github.com/digidem/CoMapeo-mobile/pull/73#discussion_r1357246210). the gist is that i think you need some separate client state to represent whether or not to enter the device naming flow which is updated based on the mutation later on, and conditionally render based on that

the issue with this is that retrieving deviceName is async. So i would need to create another wrapper, and only render the nav container when deviceName is established...I think it might just be easier to not conditionally render in this case

**Comment by ErikSin** [comment]
Closing as this should be broken up into 2 separate Prs

**Pull request closed without merging**
