### PR TITLE
feat: update app icon and splash screen image

### PR DESCRIPTION
**Pull request by achou11**
also replaces react-native-bootsplash with expo-splash-screen

Reinstates the changes from #301 , which were lost on the main branch due to some git history cleaning

### CODE REVIEW

**Review by ErikSin — CHANGES_REQUESTED** [review]
There are a couple problems on my screen. I took a screen recording

Visually, the icon and and the splash screen are really blown up.

And then on first opening the app, the splash screen works as intended.

But when the app goes in the background (not closed) and then goes back into the foreground the splash screen is being re-initialzed and then getting stuck on that screen

https://github.com/digidem/comapeo-mobile/assets/67773827/bf9b9764-13c5-4ada-82fb-e654f06b4a8a

**Comment by achou11** [comment]
@ErikSin believe i've fixed this via https://github.com/digidem/comapeo-mobile/pull/329/commits/7360158bce063ec54b29058620b80603d0b6f374. can you confirm?

**Review by ErikSin — APPROVED** [review]
There is still a slight issue with the icon being really big (Samsung s20 on Android 13). But im going to merge and Ill open a ticket for that

**Comment by achou11** [comment]
for posterity, the issue was due to Erik not rerunning the prebuild before rebuilding the app locally. after doing that, both the visual and functional fixes worked

**Pull request merged**
